name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: npm install
      - run: npm run build
      - run: npm run format
      - run: npm run lint
      - run: npm run package
      - run: npm run test
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        version:
          #- ''
          #- v1
          #- v1.4
          #- v1.4.2
          - latest
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0' # fixme should works without this too
      - uses: ./
        id: repoman1
        with:
          version: ${{ matrix.version }}
          args: ./_samples/go-binary-docker
      - name: Check outputs
        run: |
          echo "version = ${{ steps.repoman1.outputs.version }}"
          echo "has-go = ${{ steps.repoman1.outputs.has-go }}"
          echo "has-go-library = ${{ steps.repoman1.outputs.has-go-library }}"
          echo "has-go-binary = ${{ steps.repoman1.outputs.has-go-binary }}"
          echo "has-docker = ${{ steps.repoman1.outputs.has-docker }}"
      - uses: ./
        id: repoman2
        with:
          version: ${{ matrix.version }}
          args: ./_samples/go-binary
      - name: Check outputs
        run: |
          echo "version = ${{ steps.repoman2.outputs.version }}"
          echo "has-go = ${{ steps.repoman2.outputs.has-go }}"
          echo "has-go-library = ${{ steps.repoman2.outputs.has-go-library }}"
          echo "has-go-binary = ${{ steps.repoman2.outputs.has-go-binary }}"
          echo "has-docker = ${{ steps.repoman2.outputs.has-docker }}"
      - uses: ./
        id: repoman3
        with:
          version: ${{ matrix.version }}
          args: ./_samples/go-library
      - name: Check outputs
        run: |
          echo "version = ${{ steps.repoman3.outputs.version }}"
          echo "has-go = ${{ steps.repoman3.outputs.has-go }}"
          echo "has-go-library = ${{ steps.repoman3.outputs.has-go-library }}"
          echo "has-go-binary = ${{ steps.repoman3.outputs.has-go-binary }}"
          echo "has-docker = ${{ steps.repoman3.outputs.has-docker }}"
